# Welcome to Jekyll!

# Website settings
title: "Hongyan Wang"
description: "Personal website of Hongyan Wang"
keywords: "Hongyan Wang, Math, Programming, PhD"
baseurl: "/"
url: "http://hongyan0627.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Hongyan Wang'
  first_name: 'Hongyan'
  last_name: 'Wang'
  email: 'hongyan0627@gmail.com'
  linkedin_username: 'https://www.linkedin.com/in/hongyan-wang-19a99176'
  github_username: 'Hongyan0627'
  head_img: 'static/img/landing/picture.png'
  desc: 'I am a fourth year PhD student in math department of Tufts University.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  # - id: 'career'
  #   i18n: 'nav.career'
  #   name: 'Career'
  #   tpl: 'career.html'
  #   css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'publications'
    i18n: 'nav.publications'
    name: 'Publications'
    tpl: 'publications.html'
    css: 'publications'

# localization
# languages:
#   - locale: 'en'
#     flag: 'static/img/flags/United-States.png'
  # - locale: 'zh'
  #   flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
# donate:
#   wechat: 'static/img/pay/wechat.png'
#   alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  # uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  # id: UA-73784599-1

# growingIO
gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

